<?php
/**
 * Theme Functions File
 *
 * This file contains the core functions and setup for the theme.
 * It registers theme features, enqueues scripts and styles, defines custom functions,
 * and hooks into WordPress actions and filters.
 *
 * @package DaniloParraJr\Theme;
 * @since 1.0.0
 */

namespace DaniloParraJr\Theme;
const BUILD_DIR   = '/build';
const STYLES_DIR  = BUILD_DIR . '/css';
const SCRIPTS_DIR = BUILD_DIR . '/js';
const VENDOR_DIR  = '/assets/vendor';

require_once get_theme_file_path( '/includes/blocks/post-date.php' );

/**
 * Enqueues block-specific stylesheets found within a specified theme directory.
 *
 * This function scans a given directory (using `glob`) for CSS files. For each CSS file found,
 * it constructs a block name using the provided namespace and the filename. It then attempts
 * to locate a corresponding `.asset.php` file (generated by @wordpress/scripts)
 * to retrieve dependencies and version information. Finally, it enqueues the stylesheet
 * for the constructed block name using `wp_enqueue_block_style()`.
 *
 * @since 1.0.0
 *
 * @param string $theme_dir       A glob-compatible path string relative to the theme's template
 * directory, used to find CSS files.
 * Example: '/src/scss/blocks/core/*.css' to find all CSS files
 * in the 'wp-content/themes/experi/src/scss/blocks/core/' directory.
 * @param string $block_namespace Optional. The namespace for the blocks these styles apply to.
 * Defaults to 'core'. Examples: 'core', 'yoast'.
 * @return void
 *
 * @uses get_template_directory() To get the theme's root directory path.
 * @uses basename() To extract the filename from the path.
 * @uses get_theme_file_path() To get the system path to theme files.
 * @uses get_theme_file_uri() To get the URI to theme files.
 * @uses wp_get_theme() To get theme information like version.
 * @uses file_exists() To check for the existence of asset files.
 * @uses is_readable() To check if asset files are readable.
 * @uses wp_enqueue_block_style() To enqueue the stylesheet for a specific block.
 * @global string STYLES_DIR Expected to be defined, pointing to the styles directory path
 * relative to the theme root (e.g., 'src/scss').
 */
function enqueue_dir_block_stylesheets( string $theme_dir, string $block_namespace = 'core' ): void {
	// Scan our styles folder to locate block styles.
	$files             = glob( get_stylesheet_directory() . $theme_dir );
	$theme_text_domain = wp_get_theme()->get( 'TextDomain' );

	if ( $files ) {
		foreach ( $files as $file ) {
			$filename   = basename( $file, '.css' );
			$block_name = "$block_namespace/$filename";

			// Construct paths using STYLES_DIR. Ensure STYLES_DIR is defined.
			// If STYLES_DIR is not defined, this will cause issues.
			$base_style_path = STYLES_DIR . "/blocks/$block_namespace/{$filename}";
			$asset_file_path = get_theme_file_path( "{$base_style_path}.asset.php" );
			$css_file_uri    = get_theme_file_uri( "{$base_style_path}.css" );
			$css_file_path   = get_theme_file_path( "{$base_style_path}.css" );

			$block_stylesheet = array(
				'handle' => "{$theme_text_domain}-{$block_namespace}-{$filename}-block-style",
				'src'    => $css_file_uri,
				'path'   => $css_file_path,
				'deps'   => array(),
				'ver'    => wp_get_theme()->get( 'Version' ),
			);

			if ( file_exists( $asset_file_path ) && is_readable( $asset_file_path ) ) {
				$asset = include $asset_file_path;

				if ( isset( $asset['dependencies'] ) ) {
					$block_stylesheet['deps'] = $asset['dependencies'];
				}

				if ( isset( $asset['version'] ) ) {
					$block_stylesheet['ver'] = $asset['version'];
				}
			}

			wp_enqueue_block_style(
				$block_name,
				$block_stylesheet
			);
		}
	}
}

/**
 * Enqueues theme stylesheets and JavaScript files.
 *
 * This function handles the conditional loading of CSS and JS assets
 * based on the current page or context. It also dequeues specific
 * styles from plugins or core if needed.
 *
 * @since 1.0.0
 *
 * @global string STYLES_DIR Path to the theme's CSS directory, relative to the theme root.
 * @global string SCRIPTS_DIR Path to the theme's JavaScript directory, relative to the theme root.
 *
 * @uses wp_get_theme() To retrieve theme information like TextDomain and Version.
 * @uses wp_dequeue_style() To remove unwanted stylesheets.
 * @uses wp_enqueue_style() To add theme stylesheets.
 * @uses wp_enqueue_script() To add theme JavaScript files.
 * @uses get_theme_file_uri() To get the URI to a file in the theme.
 * @uses is_front_page() To check if the current page is the front page.
 * @uses is_category() To check if the current page is a category archive.
 * @uses is_tag() To check if the current page is a tag archive.
 * @uses is_singular() To check if the current page is a singular post/page/CPT.
 *
 * @return void
 */
function theme_assets() {
	$theme         = wp_get_theme();
	$theme_handle  = sanitize_key( $theme->get( 'TextDomain' ) );
	$theme_version = $theme->get( 'Version' );

	// --- Dequeue Styles ---
	// Remove default term description styles.
	wp_dequeue_style( 'wp-block-term-description' );

	// --- Enqueue Main Site Assets ---
	wp_enqueue_style(
		$theme_handle . '-site',
		get_theme_file_uri( STYLES_DIR . '/site.css' ),
		array(),
		$theme_version
	);

	if ( is_archive() || is_home() ) {
		wp_enqueue_style(
			$theme_handle . '-archive',
			get_theme_file_uri( STYLES_DIR . '/archive.css' ),
			array(),
			$theme_version
		);
	}
}
add_action( 'wp_enqueue_scripts', __NAMESPACE__ . '\\theme_assets' );


/**
 * Enqueue block stylesheets.
 *
 * @link https://developer.wordpress.org/themes/features/block-stylesheets/
 * @return void
 */
function enqueue_core_block_stylesheets() {
	enqueue_dir_block_stylesheets( STYLES_DIR . '/blocks/core/*.css' );
}
add_action( 'init', __NAMESPACE__ . '\\enqueue_core_block_stylesheets' );

/**
 * Registers custom block styles for various core Gutenberg blocks.
 *
 * This function defines an array of block styles, including their names,
 * labels, and optional inline CSS. It then iterates through this array
 * and registers each style using the `register_block_style()` function.
 *
 * The styles are applied to blocks such as 'core/button', 'core/list',
 * and 'core/post-terms', enhancing their appearance and providing
 * more design options in the block editor.
 *
 * @since 1.0.0 (or your theme/plugin version)
 * @uses register_block_style() To register individual block styles.
 * @return void
 */
function register_block_styles() {
	$block_styles = array(
		'core/button'          => array(
			array(
				'name'  => 'link',
				'label' => __( 'Link', 'experi-theme' ),
			)
		),
		'core/categories'          => array(
			array(
				'name'  => 'badges',
				'label' => __( 'Badges', 'experi-theme' ),
			),
			array(
				'name'  => 'columns',
				'label' => __( 'Columns', 'experi-theme' ),
			)
		),
	);

	foreach ( $block_styles as $block => $block_style_arr ) {
		foreach ( $block_style_arr as $block_style_item ) {
			register_block_style( $block, $block_style_item );
		}
	}
}
add_action( 'init', __NAMESPACE__ . '\\register_block_styles' );

/**
 * Theme setup function.
 *
 * This function runs after the theme is initialized.
 * It registers support for various WordPress features and setups.
 */
function theme_setup() {
	// Add support for editor styles and load the editor stylesheet.
	add_editor_style( 'build/css/editor.css' );

	// Remove core block patterns.
	remove_theme_support( 'core-block-patterns' );

	// Disable remote block patterns.
	add_filter( 'should_load_remote_block_patterns', '__return_false' );
}
add_action( 'after_setup_theme', __NAMESPACE__ . '\\theme_setup' );

add_filter( 'get_the_archive_title_prefix', '__return_empty_string' );