// WordPress webpack config.
const defaultConfig = require("@wordpress/scripts/config/webpack.config");

// Plugins.
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts");

// Utilities.
const path = require("path");

const DependencyExtractionWebpackPlugin = require("@wordpress/dependency-extraction-webpack-plugin");

const { fromProjectRoot } = require("@wordpress/scripts/utils/file");

function getProjectSourcePath() {
  return process.env.WP_SOURCE_PATH || "src";
}

const { sync: glob } = require("fast-glob");

function getStylesEntryPoints() {
  const stylePaths = glob("scss/**/!(_*).scss", {
    absolute: false,
    cwd: fromProjectRoot(getProjectSourcePath()),
  });

  let entryPoints = {};

  if (stylePaths.length > 0) {
    for (const stylePath of stylePaths) {
      let fileName = path.basename(stylePath, path.extname(stylePath));
      let entryName = path.dirname(stylePath).replace("scss", "css");
      entryPoints = {
        ...entryPoints,
        ...{
          [path.join(entryName, fileName)]: path.resolve(
            fromProjectRoot(getProjectSourcePath()),
            stylePath,
          ),
        },
      };
    }
  }

  return entryPoints;
}

function getScriptsEntryPoints() {
  const scriptPaths = glob("js/**/*.js", {
    absolute: false,
    cwd: fromProjectRoot(getProjectSourcePath()),
  });

  let entryPoints = {};

  if (scriptPaths.length > 0) {
    for (const scriptPath of scriptPaths) {
      let fileName = path.basename(scriptPath, path.extname(scriptPath));
      let entryName = path.dirname(scriptPath);

      entryPoints = {
        ...entryPoints,
        ...{
          [path.join(entryName, fileName)]: path.resolve(
            fromProjectRoot(getProjectSourcePath()),
            scriptPath,
          ),
        },
      };
    }
  }

  return entryPoints;
}

const pluginsToRemove = ["RtlCssPlugin", "DependencyExtractionWebpackPlugin"];

// @link - https://developer.wordpress.org/themes/advanced-topics/build-process/
module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      ...getStylesEntryPoints(),
      ...getScriptsEntryPoints()
    },
    plugins: [
      ...defaultConfig.plugins.filter((plugin) => {
        return !pluginsToRemove.includes(plugin.constructor.name);
      }),

      // Removes the empty `.js` files generated by webpack but
      // sets it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
      }),
      new DependencyExtractionWebpackPlugin({
        requestToExternal( request ) {
          if ( request === 'experi-theme-headroom' ) {
            return 'Headroom';
          }
        }
      }),
    ],
  },
};
